name: Build LaTeX document

on: [push]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tese.tex
      - name: Check the files in the directory
        run: ls -la
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: tese.pdf
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get latest release tag
        id: get_latest_release
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - name: Increment version
        id: increment_version
        run: |
          new_tag=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.new_tag }}
        run: |
          if gh release view "$tag"; then
            echo "Release already exists"
            exit 0
          else
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${tag#v}" \
                --generate-notes
          fi
      - name: Upload PDF to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.new_tag }}
        run: |
          gh release upload "$tag" PDF.zip
