name: Build LaTeX document

on: [push]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tese.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: tese.pdf
          path: tese.pdf
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get latest release tag
        id: get_latest_release
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - name: Increment version
        id: increment_version
        run: |
          if [ -z "$latest_tag" ]; then
            new_tag="v1.0.0"
          else
            new_tag=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')
          fi
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.increment_version.outputs.new_tag }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes
      - name: Upload PDF to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.increment_version.outputs.new_tag }}
        run: |
          gh release upload "$tag" tese.pdf
